# syntax=docker/dockerfile:1

# Bump these together if you need a newer toolchain — check available
# combinations at https://hub.docker.com/r/hexpm/elixir/tags
ARG ELIXIR_VERSION=1.17.3
ARG OTP_VERSION=27.1.2
ARG DEBIAN_VERSION=bookworm-20241016-slim
ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} AS builder

# git: heroicons/daisyui are fetched as sparse git checkouts (mix.exs), not
# hex packages. nodejs/npm: maplibre-gl (assets/package.json) is bundled by
# esbuild at asset-build time, so it must be present before `mix assets.deploy`.
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends build-essential git curl ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y --no-install-recommends nodejs && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mix local.hex --force && \
    mix local.rebar --force

ENV MIX_ENV=prod

# Set to "true" to build on a host whose CPU lacks the features (e.g. AVX2)
# the default explorer/Polars NIF assumes — see config/config.exs.
ARG EXPLORER_USE_LEGACY_ARTIFACTS=false
ENV EXPLORER_USE_LEGACY_ARTIFACTS=${EXPLORER_USE_LEGACY_ARTIFACTS}

WORKDIR /app

COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV

COPY config config
RUN mix deps.compile

COPY assets/package.json assets/package-lock.json assets/
RUN npm ci --prefix assets

COPY priv priv
COPY lib lib
COPY assets assets

# assets.setup installs the standalone tailwind/esbuild binaries. Tailwind
# needs phoenix-colocated/flockademic/colocated.css, generated by the
# :phoenix_live_view compiler pass (mix.exs `compilers:`), so `mix compile`
# has to run before assets.deploy builds+minifies CSS/JS (including the
# maplibre worker bundle) and digests the result.
RUN mix assets.setup && mix compile && mix assets.deploy

RUN mix release

FROM ${RUNNER_IMAGE} AS runtime

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libstdc++6 openssl libncurses6 locales ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/* && \
    sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV MIX_ENV=prod
ENV PHX_SERVER=true

WORKDIR /app

RUN useradd --system --create-home --shell /bin/false flockademic

COPY --from=builder --chown=flockademic:flockademic /app/_build/${MIX_ENV}/rel/flockademic ./
COPY --chown=flockademic:flockademic docker/entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

USER flockademic

EXPOSE 4000

ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["/app/bin/flockademic", "start"]
